FROM golang:1.3.3-wheezy

RUN go get github.com/tools/godep
RUN go get github.com/revel/cmd/revel

ENV SHA <%= `git rev-parse --short HEAD`.strip %>

RUN git clone https://github.com/darkhelmet/dashvee.git /go/src/github.com/darkhelmet/dashvee

WORKDIR /go/src/github.com/darkhelmet/dashvee

RUN git reset --hard $SHA

RUN godep go install ./...

ENV PATH   /go/src/github.com/darkhelmet/dashvee/Godeps/_workspace/bin:$PATH
ENV GOPATH /go/src/github.com/darkhelmet/dashvee/Godeps/_workspace:$GOPATH

ENV ASSET_HOST      http://cf.verboselogging.com
ENV CANONICAL_HOST  verboselogging.com
ENV GOMAXPROCS      4
ENV TZ              Canada/Mountain

EXPOSE 80
CMD revel run github.com/darkhelmet/dashvee prod 80
